### CREATE LIKE TO VIDEO (USER)
POST localhost:8080/video/like/create
Authorization: Bearer
Content-Type: application/json

{
  "videoId": "cb6466b0-c697-447b-bd24-fe4d13d5e7b2",
  "likeType": "LIKE"
}

### DELETE LIKE (USER)
DELETE localhost:8080/video/like/delete/1
Authorization: Bearer

### GET VIDEOS  (OWNER)
GET localhost:8080/video/like/my/liked
Authorization: Bearer

### GET USER LIKED VIDEOS (ADMIN)
GET http://localhost:8080/video/like/user/liked/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzE4OTMwMzgsInVzZXJuYW1lIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjcxOTc5NDM4LCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.Ls2dqg8dIDGGVOT5rzLRd_SSCS8KGGWFzbDlTOPXe8BhDKA9T6nt664HLWz4vI7Pm_BENnowYGavlf-zCqFmHA