
POST http://localhost:8080/api/v1/attach/public/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="BBGLlEO.JPEG"

#< C:\Users\Элмурод\Pictures\test.jpg
C:\Users\Deweloper\OneDrive\Рабочий стол\test\BBGLlEO.JPEG

### video

POST http://localhost:8080/api/v1/attach/public/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test1.mp4"

< C:\Users\Элмурод\Pictures\test1.mp4

### open file
GET localhost:8080/api/v1/attach/public/open/bd7f5411-fe6c-4661-bae1-b324ed270621.jpg


### download
GET localhost:8080/api/v1/attach/public/download/adee08ad-5ca1-4914-86c6-47ba1def3488.mp4

### pagination

GET localhost:8080/api/v1/attach/private/admin/pagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjg1NjQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDQxNDk2NCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.sdxdsxhQ0dmwmk0hW94fuR2zObyeHhj9qKHZ3p29teSIJONnME4XanU8DKnIUWXC6VzJfFmJRrhLrFkALunlrA

### delete by id
DELETE localhost:8080/api/v1/attach/private/delete/3ccc206d-ac32-43ca-b7e7-6ab6a53c7bab
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjg1NjQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDQxNDk2NCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.sdxdsxhQ0dmwmk0hW94fuR2zObyeHhj9qKHZ3p29teSIJONnME4XanU8DKnIUWXC6VzJfFmJRrhLrFkALunlrA
