### create channel
POST localhost:8080/api/v1/channel/private/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NzQ0MDksImVtYWlsIjoiZGFzdG9ubmF6YXJvdjA5MTBAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDc2MDgwOSwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.xFQv2k7C6Zp4hS4aDVFTqsucHl_GNZtjh3X84qOMthIrmY00ks6BihI1Dr_Xrfpo_Yx4RFxHnI_0G8CsHmNu6g
Content-Type: application/json

{
  "name": "Java Uz"
}

### update channel photo
PUT localhost:8080/api/v1/channel/private/update/c92b898d-2664-4a32-b0cc-16fa892d5e8e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMzQ5NzgsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDIxMzc4LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.H8_job6PShj1CHt7ezxSpKlCIsWzNwO1Wvbph8xWxyk8JvTTI719vNKko3NQu59T5mRGmBSfV-mhOVq1j2pA-w


### update channel banner
PUT localhost:8080/api/v1/channel/private/updateBanner/94cfad48-1d35-4ed0-816c-ca6d99acb42e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMzQ5NzgsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDIxMzc4LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.H8_job6PShj1CHt7ezxSpKlCIsWzNwO1Wvbph8xWxyk8JvTTI719vNKko3NQu59T5mRGmBSfV-mhOVq1j2pA-w


### pagination
GET localhost:8080/api/v1/channel/private/admin/pagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzOTMwOTIsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDQ3OTQ5MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.s1fDz6RufIZ96PJ4w2PVJT2dIUUGGH6D1uOFvQ_7uzjqHBQZUiLUCxOvk3vueDH7ze8XjekaP18knNanAMLlkQ

### get channel by id
GET localhost:8080/api/v1/channel/public/6cff4172-bca2-47f2-b0c6-afb506e89521


### change status
GET localhost:8080/api/v1/channel/private/admin/6cff4172-bca2-47f2-b0c6-afb506e89521
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzOTMwOTIsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDQ3OTQ5MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.s1fDz6RufIZ96PJ4w2PVJT2dIUUGGH6D1uOFvQ_7uzjqHBQZUiLUCxOvk3vueDH7ze8XjekaP18knNanAMLlkQ


### user channel
GET  localhost:8080/api/v1/channel/private/getChannel
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMzQ5NzgsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDIxMzc4LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.H8_job6PShj1CHt7ezxSpKlCIsWzNwO1Wvbph8xWxyk8JvTTI719vNKko3NQu59T5mRGmBSfV-mhOVq1j2pA-w


### update channel detail
POST localhost:8080/api/v1/channel/private/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMzQ5NzgsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDIxMzc4LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.H8_job6PShj1CHt7ezxSpKlCIsWzNwO1Wvbph8xWxyk8JvTTI719vNKko3NQu59T5mRGmBSfV-mhOVq1j2pA-w
Content-Type: application/json

{
  "name": "Code uz"
}