

### cooment create
POST localhost:8080/api/v1/comment/private/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMzQ5NzgsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDIxMzc4LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.H8_job6PShj1CHt7ezxSpKlCIsWzNwO1Wvbph8xWxyk8JvTTI719vNKko3NQu59T5mRGmBSfV-mhOVq1j2pA-w
Content-Type:  application/json

{
  "title": "Code uz",
  "attachId":"e1f7b0d7-4929-4476-b198-ed60fc925ebd"
}


### comment update
PUT localhost:8080/api/v1/comment/private/update/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjg3OTYsImVtYWlsIjoibXV5c2lub3ZtdXhzaW5iZWszM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDE1MTk2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.ikXJpLlq5mN3QyuQtJLr822Txzizz8pYFBzdnTdVD6L7v86-1Ov_B9oz4QqXO48hIIKA61OdIwMYZqKPYQcDFw
Content-Type:  application/json


### comment  delete
DELETE localhost:8080/api/v1/comment/private/delete/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjg3OTYsImVtYWlsIjoibXV5c2lub3ZtdXhzaW5iZWszM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDE1MTk2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.ikXJpLlq5mN3QyuQtJLr822Txzizz8pYFBzdnTdVD6L7v86-1Ov_B9oz4QqXO48hIIKA61OdIwMYZqKPYQcDFw
Content-Type:  application/json


### comment getPaging
GET localhost:8080/api/v1/comment/public/getPaging/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjg3OTYsImVtYWlsIjoibXV5c2lub3ZtdXhzaW5iZWszM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDE1MTk2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.ikXJpLlq5mN3QyuQtJLr822Txzizz8pYFBzdnTdVD6L7v86-1Ov_B9oz4QqXO48hIIKA61OdIwMYZqKPYQcDFw
Content-Type:  application/json

### comment getByProfileId
GET localhost:8080/api/v1/comment/public/getByProfileId/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjg3OTYsImVtYWlsIjoibXV5c2lub3ZtdXhzaW5iZWszM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDE1MTk2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.ikXJpLlq5mN3QyuQtJLr822Txzizz8pYFBzdnTdVD6L7v86-1Ov_B9oz4QqXO48hIIKA61OdIwMYZqKPYQcDFw
Content-Type:  application/json

### comment getByProfile
GET localhost:8080/api/v1/comment/public/getByProfile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjg3OTYsImVtYWlsIjoibXV5c2lub3ZtdXhzaW5iZWszM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDE1MTk2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.ikXJpLlq5mN3QyuQtJLr822Txzizz8pYFBzdnTdVD6L7v86-1Ov_B9oz4QqXO48hIIKA61OdIwMYZqKPYQcDFw
Content-Type:  application/json