
###
PUT http://localhost:8080/api/v1/comment_like/private/like/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ5NTQ4NzcsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NTA0MTI3NywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.53JnSLScNkUbjXtmEYrP_1TE7le2vwTEMhPTvfNJ9w5vH-dxyv5FwhbknK5gAY6Y-Ae1iO3QEnJaqHNoI8K5hQ



###
PUT http://localhost:8080/api/v1/comment_like/private/dislike/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ5NTQ4NzcsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NTA0MTI3NywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.53JnSLScNkUbjXtmEYrP_1TE7le2vwTEMhPTvfNJ9w5vH-dxyv5FwhbknK5gAY6Y-Ae1iO3QEnJaqHNoI8K5hQ


###
DELETE http://localhost:8080/api/v1/comment_like/private/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ4NDk1NzYsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDkzNTk3NiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.j1ZMriBcSuViIvN2FnG4bFYCpRv7-xd3A1bKjHWAFvbuk2wAGNEZwO67aUzdmToqU0AurAvMXc2313z3hwn1eQ
