

### create video
POST localhost:8080/api/v1/video/private/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NzQ0MDksImVtYWlsIjoiZGFzdG9ubmF6YXJvdjA5MTBAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDc2MDgwOSwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.xFQv2k7C6Zp4hS4aDVFTqsucHl_GNZtjh3X84qOMthIrmY00ks6BihI1Dr_Xrfpo_Yx4RFxHnI_0G8CsHmNu6g
Content-Type:  application/json

{
  "title": "Comment_Uz",
  "attachId":"5b50b8f0-b593-47a6-8bd7-3dcdaef6fcef"
}


### update video
PUT localhost:8080/api/v1/video/private/update/b24a4737-4439-402f-a702-d74faf1eb0f3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0Nzk4NTQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NTY2MjU0LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Bhu7WKzc1JH2MAIkXp8WhkN_n5N9hO2D5da_FenEV4l8odrJfz3IWVkPFUX-cvDzQ1tspYGvwpyRIjkdnsLe9g
Content-Type:  application/json

{
  "title": "Code uz brain academy",
  "description": "Brain academyda java kurslari"
}


### change status video
PUT localhost:8080/api/v1/video/private/status/d0865c47-0c52-4c0e-a7d2-20601aeba278
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0Nzk4NTQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NTY2MjU0LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Bhu7WKzc1JH2MAIkXp8WhkN_n5N9hO2D5da_FenEV4l8odrJfz3IWVkPFUX-cvDzQ1tspYGvwpyRIjkdnsLe9g



### increase video count
PUT localhost:8080/api/v1/video/private/view_c/d0865c47-0c52-4c0e-a7d2-20601aeba278
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0Nzk4NTQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NTY2MjU0LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Bhu7WKzc1JH2MAIkXp8WhkN_n5N9hO2D5da_FenEV4l8odrJfz3IWVkPFUX-cvDzQ1tspYGvwpyRIjkdnsLe9g


### video paging by category id

GET localhost:8080/api/v1/video/public/paging/1

### video paging by title
GET localhost:8080/api/v1/video/public/title?text=o

### get video by tag id
GET localhost:8080/api/v1/video/public/tag/3

### Get Video List Pagination (ADMIN)
GET localhost:8080/api/v1/video/private/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1NjAwNDgsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2QwMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDY0NjQ0OCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.6WWxEGf-NFbUWU3GJpxdNRNRDLJ-Q2Appu-HLQZ2-an8oGt_BepfiMhUsGA-qb3Hjov5FCDlEgMiEiJCh8RFjA


### get channel video by list pagination
GET localhost:8080/api/v1/video/public/videos/38a7bf46-56bc-490f-8914-36c9457af802