### create video
POST localhost:8080/api/v1/video/private/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0Nzk4NTQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NTY2MjU0LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Bhu7WKzc1JH2MAIkXp8WhkN_n5N9hO2D5da_FenEV4l8odrJfz3IWVkPFUX-cvDzQ1tspYGvwpyRIjkdnsLe9g
Content-Type:  application/json

{
  "title": "Code uz",
  "attachId":"c92b898d-2664-4a32-b0cc-16fa892d5e8e"
}


### update video
PUT localhost:8080/api/v1/video/private/update/b24a4737-4439-402f-a702-d74faf1eb0f3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0Nzk4NTQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NTY2MjU0LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Bhu7WKzc1JH2MAIkXp8WhkN_n5N9hO2D5da_FenEV4l8odrJfz3IWVkPFUX-cvDzQ1tspYGvwpyRIjkdnsLe9g
Content-Type:  application/json

{
  "title": "Code uz brain academy",
  "description": "Brain academyda java kurslari"
}


### change status video
PUT localhost:8080/api/v1/video/private/status/d0865c47-0c52-4c0e-a7d2-20601aeba278
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0Nzk4NTQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NTY2MjU0LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Bhu7WKzc1JH2MAIkXp8WhkN_n5N9hO2D5da_FenEV4l8odrJfz3IWVkPFUX-cvDzQ1tspYGvwpyRIjkdnsLe9g



### increase video count
PUT localhost:8080/api/v1/video/private/view_c/d0865c47-0c52-4c0e-a7d2-20601aeba278
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ0Nzk4NTQsImVtYWlsIjoic2F5ZGFsaXlldmVsbXVyb2Q5M0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NTY2MjU0LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.Bhu7WKzc1JH2MAIkXp8WhkN_n5N9hO2D5da_FenEV4l8odrJfz3IWVkPFUX-cvDzQ1tspYGvwpyRIjkdnsLe9g


### video paging by category id

GET localhost:8080/api/v1/video/public/paging/1

### video paging by title
GET localhost:8080/api/v1/video/public/title?text=o