### create playlist
POST localhost:8080/api/v1/playList/private/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjg3OTYsImVtYWlsIjoibXV5c2lub3ZtdXhzaW5iZWszM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NDE1MTk2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.ikXJpLlq5mN3QyuQtJLr822Txzizz8pYFBzdnTdVD6L7v86-1Ov_B9oz4QqXO48hIIKA61OdIwMYZqKPYQcDFw
Content-Type:  application/json

{
  "name": "ali",
  "channelId": "4u5hi4uh5iu45h",
  "description": "fkjfdjldjf",
  "status": "ROLE_PRIVATE",
  "orderNumber": "3"
}